# Generated by Django 4.2.7 on 2024-12-10 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, "Recipe name must contain at least 5 characters"
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date_deadline", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
