# Generated by Django 4.2.7 on 2024-12-11 18:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User

def get_first_user_id():
    # Return the ID of the first user (or any valid user)
    first_user = User.objects.first()
    if first_user:
        return first_user.id
    return None  # Ensure there is a return value if no users exist

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo", "0002_todo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Todo title must contain at least 5 characters"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                default=get_first_user_id,  # Use the callable to get the user's ID
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]

